import { getDownloadURL, getStorage, list, ref } from "firebase/storage";
import Head from "next/head";
import { useEffect, useState } from "react";
import BannerArea from "../components/Home/BannerArea";
import BrandArea from "../components/Home/BrandArea";
import CategoryArea from "../components/Home/CategoryArea";
import Cta from "../components/Home/Cta";
import Footer from "../components/Home/Footer";
import Header from "../components/Home/Header";
import HeroArea from "../components/Home/HeroArea";
import Products from "../components/Home/Products";
import Subscribe from "../components/Home/Subscribe";
import Testimonial from "../components/Home/Testimonial";
import TrendingLandmark from "../components/Home/TrendingLandmark";

export default function Home() {
  const [videos, setVideos] = useState([]);
  const storage = getStorage();
  const getList = async () => {
    const listRef = ref(storage);
    const currentPage = await list(listRef, { maxResults: 4 });
    const urls = await Promise.all(
      currentPage.items.map(async (el) => {
        const url = await getDownloadURL(el);
        return url;
      })
    );
    console.log({ urls });
    setVideos(urls);
  };
  useEffect(() => {
    if (videos) {
      getList();
    }
  }, []);
  return (
    <>
      <Head>
        <title>Markit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {videos?.map((url) => (
        <video style={{ height: 360, width: "100%" }} controls>
          <source src={url} type="video/mp4"></source>
          support videos. Sorry, your browser doesn't
        </video>
      ))}

      <HeroArea />
      <CategoryArea />
      <TrendingLandmark />
      <Subscribe />
      <Products />
      <Cta />
      <BrandArea />
      <Testimonial />
      <BannerArea />
      <Footer />
    </>
  );
}
